# Generated by Django 2.1.1 on 2018-10-16 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ilstaApp', '0003_auto_20181010_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 16, 14, 10, 17, 542858, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='capital',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 14, 10, 17, 546408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 14, 10, 17, 558454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 14, 10, 17, 544511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 14, 10, 17, 548315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='tipps',
            field=models.TextField(blank=True, default='No Tipps!!'),
        ),
        migrations.CreateModel(
            name='TaskSolving',
            fields=[
                ('timestamped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ilstaApp.TimeStamped')),
                ('text', models.TextField(blank=True, default='No text!!')),
            ],
            bases=('ilstaApp.timestamped',),
        ),
    ]
